Adds the c# project.
Star-Academy/Summer1403-SE-Team06 pull request #1
Opened 2024-07-20 14:33 UTC by mobinbr

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +            Student studentInfo = studentsMap[currentStudent.StudentNumber];
در رابطه با استفاده کردن یا نکردن از var به جای type شیء، این ویدیو رو ببینید؛ بعد ریپلای کنید به همین کامنت که به نظرتون اینجا var استفاده کردن خوبه یا نه
https://www.youtube.com/watch?v=Sa184usBTXk

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +        var students = JsonSerializer.Deserialize<List<Student>>(File.ReadAllText(StudentsFilePath));
تو این دو خط که دارید از فایل می‌خونید، خوبه که ارورهای احتمالی‌ش هم هندل بکنید، مثل وجود نداشتن فایل با این آدرس

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +        for (var i = 0; i < topStudents.Count; i++)
بهتره به جای for از foreach استفاده کنید که خوانایی بهتری هم داره. موقع چاپ هم چون سوال ازتون چاپ عدد رو نخواسته خود i مستقلا لازم نمیشه

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +    private record GpaInfo(int StudentNumber, double Gpa);
اسما ترجیحا کامل و مفهوم باشه و اینطوری مختصر نباشه

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +    private record GpaInfo(int StudentNumber, double Gpa);
این رکورد و دو تا کلاس دیگه رو خوبه هر کدومو تو یه فایل .cs جدا تعریف کرد که تمیزتر باشه

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +    public int StudentNumber {get; set;}
فیلدهای این کلاس و کلاس پایینی متود set شون استفاده نشده

2024-07-21 07:44 UTC, HamedSY commented on students-project/Program.cs
> +public class Program {
برای فایلتون بهتره namespace هم مشخص کنید

2024-07-21 07:51 UTC, HamedSY commented on students-project/Program.cs
> +﻿using System.Text.Json;
درباره convention های اسم برنچ و مسیج کامیت‌ها این دو تا لینک رو ببینید خوبه برای دفعات بعدی

https://medium.com/@shinjithkanhangad/git-good-best-practices-for-branch-naming-and-commit-messages-a903b9f08d68

https://www.conventionalcommits.org/en/v1.0.0/

2024-07-21 08:54 UTC, rajabi-m commented on students-project/Program.cs
> +﻿using System.Text.Json;
درسته برنچ full-text-search رو هم زدیم الان ولی از این به بعد سعی میکنیم رعایت کنیم.

2024-07-21 08:56 UTC, rajabi-m commented on students-project/Program.cs
> +public class Program {
با توجه به اینکه تمرین جزئی بود کلش رو توی یدونه فایل زدیم و از namespace استفاده نکردیم ولی درستش میکنیم.

2024-07-21 10:00 UTC, mobinbr commented on students-project/Program.cs
> +    public int StudentNumber {get; set;}
برای deserialize کردن فایل ها از set استفاده شده

2024-07-21 10:03 UTC, mobinbr commented on students-project/Program.cs
> +    private record GpaInfo(int StudentNumber, double Gpa);
اسم ها اصلاح شد و به GpaInformation تغییر داده شد
توی ا[ین کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/9082b46b46a247ecbf7119994d2772bddc228f7b) رفع شد

2024-07-21 10:05 UTC, mobinbr commented on students-project/Program.cs
> +        for (var i = 0; i < topStudents.Count; i++)
از i برای چاپ قشنگ تر خروجی استفاده کرده بودیم ولی بخاطر خوانایی بهتر به foreach تغییر دادیم
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/9082b46b46a247ecbf7119994d2772bddc228f7b) اصلاح شد

2024-07-21 10:05 UTC, rajabi-m commented on students-project/Program.cs
> +    private record GpaInfo(int StudentNumber, double Gpa);
اون رکورد تنها استفاده اش برای خروجی تابع GetTopStudents هست برای همین همینجا باشه به نظرم بهتره ولی خب درباره کلاس های Student و StudentScore حق با شماست.
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/17e4350d69b5617c75f7b2908088904f92240eaa) رفع شد.

2024-07-21 10:06 UTC, rajabi-m commented on students-project/Program.cs
> +        var students = JsonSerializer.Deserialize<List<Student>>(File.ReadAllText(StudentsFilePath));
درسته ارور هندلیگ رو باید اضافه کنیم.
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/f0bc6e441874a3802802f0d0945c9b41d06dda6e) اضافه شد.

2024-07-21 10:07 UTC, mobinbr commented on students-project/Program.cs
> +            Student studentInfo = studentsMap[currentStudent.StudentNumber];
باتوجه به ویدیو توی این مورد خوب نبود
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/9082b46b46a247ecbf7119994d2772bddc228f7b) این مورد و موارد مشابه اصلاح شد

2024-07-21 10:50 UTC, HamedSY commented on students-project/Program.cs
> +        List<StudentScore> studentScores = new();
تو این شرایط، بهتره از var استفاده کنید، و type رو توی new مشخص کنید. یعنی مثلا اینطوری
```c#
var students = new List<Student>()
```

2024-07-21 10:50 UTC, HamedSY commented on students-project/Program.cs
> +            Console.WriteLine(exception.Message);
با توجه به اینکه توی catch جفت این فایلا دارید یه کار می‌کنید، از یه try catch استفاده بشه بهتره

2024-07-21 10:50 UTC, HamedSY commented on students-project/Program.cs
> +        List<GpaInformation> topStudents = GetTopStudents(studentScores);
کلا ترجیح بر استفاده از var هست و اسم‌گذاری بهتر، همون‌طور که تو اون ویدیو هم nick chapsas می‌گفت.
اینجا مثلا لیست gpa بودن رو به نظرم تو اسم بهتره نشون داد. مثلا اسم متغیر بشه topStudentsGpas و از var استفاده بشه
چون وقتی اسمشو می‌ذاری topStudents برداشت اولیه اینه که جنسش لیست Student هست

این کامنت درباره اسم متود GetTopStudents و پایین توی foreach هم هست

2024-07-21 10:50 UTC, HamedSY commented on students-project/Program.cs
> +    private record GpaInformation(int StudentNumber, double Gpa);
بیشتر از مختصر منظور Gpa بود :)))
ولی خب اوکیه، من خودم خیلی gpa رو نشنیده بودم ولی ظاهرا اختصار پراستفاده‌ایه

2024-07-21 10:50 UTC, HamedSY commented on students-project/Program.cs
> +            Student studentInformation = studentsMap[topStudent.StudentNumber];
این دیگه یکم سلیقه‌ایه و لازم نیست عوض کنید
ولی به نظرم اسم متغیر و اسم دیکشنری که داره ست میشه به متغیر به اندازه کافی گویا هست و میشه اینجا از var استفاده کرد

2024-07-21 10:54 UTC, rajabi-m commented on students-project/Program.cs
> +        List<StudentScore> studentScores = new();
آخه فرقی نمی کنه
توی ویدیویی که لینک کردین طرف به این روش اشاره کرد‌.

2024-07-21 10:54 UTC, HamedSY commented on students-project/Program.cs
> +    public int StudentNumber {get; set;}
اره حق با شماست
اشتباه از من بود

2024-07-21 11:42 UTC, mobinbr commented on students-project/Program.cs
> +            Console.WriteLine(exception.Message);
بله اولش داشتیم یه جور دیگه میزدیم بخاطر همین دوتاش مونده بود
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/917a847bb1d597c3fac11f916830147ed8068320) اصلاح شد

2024-07-21 11:43 UTC, mobinbr commented on students-project/Program.cs
> +    private record GpaInformation(int StudentNumber, double Gpa);
اره ما هم بخاطر اینکه خیلی پراستفادس انتخابش کردیم

2024-07-21 11:44 UTC, mobinbr commented on students-project/Program.cs
> +            Student studentInformation = studentsMap[topStudent.StudentNumber];
درسته اینجا هم var کردیم و گویا هستش
توی [این کامنت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/917a847bb1d597c3fac11f916830147ed8068320) اصلاح شد

2024-07-21 11:44 UTC, rajabi-m commented on students-project/Program.cs
> +        List<GpaInformation> topStudents = GetTopStudents(studentScores);
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/312770f522be3645003b52f1de2e6cf5592e91cf) رفع شد.

2024-07-21 12:34 UTC, HamedSY approved these changes

2024-07-21 12:34 UTC, HamedSY commented on students-project/Program.cs
> +
اینجا اینترهای اضافی زده شده
یه دونه بسه

2024-07-21 12:34 UTC, HamedSY commented on students-project/Program.cs
> +        foreach(GpaInformation topStudentGpa in topStudentsGpa)
اینجا تو foreach هم var استفاده کنید برای topStudentGpa چون اسمشو درست کردید
همین‌طور لیست topStudentsGpa

2024-07-21 14:05 UTC, AliSK81 requested changes

2024-07-21 14:05 UTC, AliSK81 commented on students-project/Program.cs
> +    private const string ScoresFilePath = @"data\scores.json";
move to resource (.resx) file

2024-07-21 14:05 UTC, AliSK81 commented on students-project/Program.cs
> +    private const int TopStudentsCount = 3;
چه فیدهایی رو const تعریف میکنیم؟

2024-07-21 14:05 UTC, AliSK81 commented on students-project/Program.cs
> +        catch (Exception exception)
catch more specific exception (why?)

2024-07-22 05:22 UTC, AliSK81 approved these changes

2024-07-22 06:21 UTC, rajabi-m commented on students-project/Program.cs
> +    private const int TopStudentsCount = 3;
فیلدهایی که مطمئن هستیم در روند اجرای برنامه مقدارشون تغییری نمی‌کنه. این فیلد هم همینطور هست.

2024-07-22 06:25 UTC, rajabi-m commented on students-project/Program.cs
> +        catch (Exception exception)
اولش اکسپشن های مربوط به اشتباه بودن نام فایل و اشکال در دیسریالایز شدن رو هندل کرده بودیم و برای هرکدام پیامی مناسب به کاربر نشان میدادیم. ولی در نهایت تصمیم بر این شد که پیام خود اکسپشن ها را به کاربر نشان دهیم زیرا آنها به اندازه کافی خوب بودند. پس در نتیجه تمامی آنها را حذف و هر اکسپشنی را با پرینت کردن پیام آن هندل کردیم.

2024-07-22 06:27 UTC, rajabi-m commented on students-project/Program.cs
> +        foreach(GpaInformation topStudentGpa in topStudentsGpa)
اینجا خیلی سلیقه ای میشه ولی به نظرم توی خط تعریف از var استفاده نکنیم بهتره چون اسم متود خوب این مفهموم رو نمیرسونه که خروجی چیه ولی توی فورایج رو var میزنیم. 👍

2024-07-22 07:40 UTC, mobinbr commented on students-project/Program.cs
> +    private const string ScoresFilePath = @"data\scores.json";
در [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/efab7411102582d5b93f721c018ec54411df5be9) انجام شد

2024-07-22 11:18 UTC, merged