Release/full text search phase1
Star-Academy/Summer1403-SE-Team06 pull request #2
Opened 2024-07-22 08:54 UTC by mobinbr

2024-07-22 11:05 UTC, AliSK81 requested changes, later dismissed

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Shared/FileReader.cs
> +        }
try to rewrite using LINQ

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Shared/InvertedIndex.cs
> +            }
try to rewrite using LINQ

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Shared/InvertedIndex.cs
> +        }
بهتر نیست فیلتر کنیم قبل اضافه کردن؟

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Shared/InvertedIndex.cs
> +        }
avoid exceptions whenever possible (why?)
check if dictionary constains key instead

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Phase1/Program.cs
> +        Console.WriteLine("Processing files...");
use ILogger

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/EnglishData/59652
add data path to .gitignore

2024-07-22 11:05 UTC, AliSK81 commented on full-text-search/Phase1/Program.cs
> +        catch(Exception exception)
handle and log more specific exceptions

2024-07-22 11:05 UTC, AliSK81 commented on students-project/Program.cs
کدهای فاز قبل اینجا چیکار میکنه؟

2024-07-22 11:31 UTC, rajabi-m commented on full-text-search/Shared/InvertedIndex.cs
> +        }
درسته
توی این حالت بازدهی برنامه بالاتر میرفت چون فقط نیاز به یک بار چک کردن هست ولی خب منطقا روش درستی نیست.
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/422d6895d6ed725622b90249de9b2b4120e10b7b) فیکس شد.

2024-07-22 11:35 UTC, rajabi-m commented on full-text-search/Shared/InvertedIndex.cs
> +        }
درسته اینجا جای درستی برای استفاده از Exception نیست چون Exception ها برای مواقعی هستن که معمولا یه اتفاق خیلی بد رخ داده و اینکه به نظر روند کد رو هم کند تر میکنن.

2024-07-22 11:54 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +        catch(Exception exception)
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/c54b0f6b3aa7034892a6f72dfcdbea9be3d7da1f) رفع شد.

2024-07-22 11:54 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +        Console.WriteLine("Processing files...");
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/c54b0f6b3aa7034892a6f72dfcdbea9be3d7da1f) اضافه شد.

2024-07-22 12:00 UTC, rajabi-m commented on full-text-search/EnglishData/59652
شرمنده بابت فشاری که به سیستمتون وارد شد :)
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/dba38515588f5cfa620b5e3fdbe08869d70852c8) فیکس شد.

2024-07-22 13:15 UTC, rajabi-m commented on students-project/Program.cs
توی این عکس رشته کامیت سبز برنچ این فاز و رشته کامیت بنفش برنچ فاز قبل هست.
متاسفانه باتوجه به اشتباهی که ما انجام دادیم. این برنچ از کامیت اولیه برنچ فاز قبل شروع شده.
به نظرتون با cherry pick میشه این مشکل رو حل کرد؟
![image](https://github.com/user-attachments/assets/305875c4-4a09-42be-a56c-615d62935744)

2024-07-22 14:13 UTC, mobinbr commented on full-text-search/Shared/FileReader.cs
> +        }
در [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/b67016ec517c241b049ad19858f984a7e08e2844) اصلاح شد

2024-07-22 14:14 UTC, mobinbr commented on full-text-search/Shared/InvertedIndex.cs
> +            }
در [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/b67016ec517c241b049ad19858f984a7e08e2844) اصلاح شد

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +        using ILoggerFactory factory = LoggerFactory.Create(builder => builder.AddConsole());
اینجا به نظرم بهتره اسم متغیر کامل‌تر باشه؛ مثلا loggerFactory. چون factory خالی گویا نیست. در این صورت با خیال راحت هم میشه از var استفاده کرد.
تو همون ویدیو Nick Chapsas هم بود که یکی از خوبیای استفاده از var اینه که شما دیگه مجبور میشی اسم کامل و خوب بذاری رو متغیرهات

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +        ILogger logger = factory.CreateLogger("Program");
اینجا هم با توجه به اسم تابع و اینکه گفتم اسم factory هم عوض بشه به loggerFactory، دیگه از var استفاده بشه

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +            if (string.IsNullOrWhiteSpace(input)) break;
اینجا اگه یه اینتر خالی بزنه کلا برنامه تموم میشه. به نظرتون اینطوری خوبه؟ مثلا احتمال داره طرف دستش بخوره.
به نظرتون بهتر نیست شرط termination بهتری بذاریم؟ روش فکر کنید ببینید چی بهتره. مثلا اگه بخوایم با وارد کردن "exit" برنامه رو تموم کنیم، اگه خواست خود کلمه exit رو سرچ کنه چی؟

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +namespace Mohaymen.FullTextSearch.Phase1;
این رو همین‌طوری می‌ذارم بخونید :) درباره convention اسم‌گذاری namespace
وگرنه این namespace تون اوکیه

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
درباره منطق یه پروژه جدا زدن برای این دو کلاس هم یه توضیحی می‌دید؟ و همین‌طور اسم "Shared" برای پروژه

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Shared/FileReader.cs
> +            .ToDictionary(file => file, file => File.ReadAllText(file));
اینجا به جای lambda expression می‌تونید از method group استفاده کنید خوشگل‌تر و خواناتر میشه
این لینکو برای توضیح بیشتر ببینید
https://www.jetbrains.com/help/rider/ConvertClosureToMethodGroup.html

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Shared/InvertedIndex.cs
> +    private Dictionary<string, HashSet<string>> InvertedIndexMap;
naming convention for private fields

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +    public static void Main()
الان چون هنوز clean code رو نخوندید خیلی نمی‌خوام تو این مسائل سخت بگیرم.
ولی خب اینجا چون مشهوده میگم.
تابع Main یه کوچولو طولانی شده و خیلی خوب و روال میشه یه چن تا متود کشید بیرون ازش

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +            logger.LogError(exception, "An error occurred while reading files.");
تو این catch ها خوبه خود exception.message هم بعد از اروری که خودتون چاپ می‌کنید چاپ کنید

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Shared/InvertedIndex.cs
> +        foreach(var file in filesContent)
اینجای توی foreach میشه از این syntax استفاده کرد:
```c#
foreach(var (filePath, fileText) in filesContent)
```

تا دیگه جدا مجبور نشید key و value دیکشنری رو بگیرید.
ولی خب خودتون یه بررسی‌ای بکنید آیا همیشه بهتره این روش؟ از لحاظ پرفورمنس فرقی داره؟

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Shared/FileReader.cs
> +            .GetFiles(folderPath)
هندل کردن ارور اگه folderPath ولید نبود

2024-07-23 08:34 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +        Dictionary<string, string> filesContent;
این dictionary که تو کلاسا و تابعای دیگه استفاده شده می‌تونه تبدیل به لیستی از یه کلاس بشه که حاوی این دوتا استرینگ filePath و fileText باشه؛ به نظرم خواناتر و بهتره

2024-07-23 09:08 UTC, rajabi-m commented on full-text-search/Shared/FileReader.cs
> +            .ToDictionary(file => file, file => File.ReadAllText(file));
درسته که این حالت خلاصه تر و خوشگل تر میشه ولی باتوجه به اینکه برای key دیکشنری از lambda استفاده کردیم به نظرمون اگر برای value هم از lambda استفاده کنیم خواناتر هست.

حالا باز به نظرتون عوضش کنیم یا نه؟

2024-07-23 09:51 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +        using ILoggerFactory factory = LoggerFactory.Create(builder => builder.AddConsole());
در [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/d8d81311393804ff6cf3b4b73189672a6973d470) اصلاح شد.

2024-07-23 09:53 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +        ILogger logger = factory.CreateLogger("Program");
درسته ولی توی [کامیت کوتاه کردن متود مین](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75) لاگر تبدیل به یک فیلد استاتیک شد و دیگه این مسائل براش مطرح نیست.

2024-07-23 09:54 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +            if (string.IsNullOrWhiteSpace(input)) break;
تصمیم بر استفاده از !q شد.
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75#diff-a8fc24a6997be73c89f08d316dd7f085a0114a0ca0f1f1b301debd8a84b6a9f7) اضافه شد.

2024-07-23 09:54 UTC, mobinbr commented on full-text-search/Phase1/Program.cs
> +        Dictionary<string, string> filesContent;
به این دلیل از dictionary استفاده می کنیم که باتوجه به منطق تابع ProcessFilesWords اونجا سرعت بالاتری داره

2024-07-23 09:54 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +namespace Mohaymen.FullTextSearch.Phase1;
ممنون حتما برسی میکنیم.

2024-07-23 09:56 UTC, mobinbr commented on full-text-search/Shared/FileReader.cs
> +            .GetFiles(folderPath)
توی Program.cs هندل شده

2024-07-23 09:56 UTC, rajabi-m commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
کلاس های FileReader و InvertedIndex  بین ۲ فاز مشترک بودن پس یک لایبری به اسم Shared ساختیم که توی هر ۲ پروژه ازش استفاده کنیم. 
به نظرمون روش خوبی هست ممنون میشم نظرتون رو بگین.

2024-07-23 09:57 UTC, rajabi-m commented on full-text-search/Shared/InvertedIndex.cs
> +    private Dictionary<string, HashSet<string>> InvertedIndexMap;
در [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75#diff-a8fc24a6997be73c89f08d316dd7f085a0114a0ca0f1f1b301debd8a84b6a9f7) رفع شد.

2024-07-23 09:57 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +    public static void Main()
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75#diff-a8fc24a6997be73c89f08d316dd7f085a0114a0ca0f1f1b301debd8a84b6a9f7) از سر و ته Main متود های مختلف کشیدیم بیرون.

2024-07-23 09:58 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +            logger.LogError(exception, "An error occurred while reading files.");
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75#diff-a8fc24a6997be73c89f08d316dd7f085a0114a0ca0f1f1b301debd8a84b6a9f7) رفع شد.

2024-07-23 09:58 UTC, mobinbr commented on full-text-search/Shared/InvertedIndex.cs
> +        foreach(var file in filesContent)
بله بررسی کردیم و متوجه شدیم که تو این حالت پرفورمنسش به دلیل pair کردن key و value یک مقدار پایین میاد ولی به دلیل خواناتر بودن تغییرش دادیم
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/commit/5341eaa698b65867f9065f6b81e3f27578f70e75) اصلاح شد

2024-07-24 06:36 UTC, HamedSY commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
کار خیلی خوبیه
فقط اسمش به نظرم conceptual باشه بهتره؛ مشخص کنه لایبرری چیکار داره می‌کنه

2024-07-24 06:42 UTC, HamedSY approved these changes

2024-07-24 06:42 UTC, HamedSY commented on full-text-search/Phase1/Program.cs
> +    private static bool LoadFilesAndIndexThem()
این تابع bool برمی‌گردونه، ولی اسمش اینو نشون نمیده
وقتی بالاتر نوشتید
`if (!LoadFilesAndIndexThem())`
خواننده کد نمی‌فهمه این شرط چیو داره بررسی می‌کنه

2024-07-24 06:49 UTC, HamedSY commented on full-text-search/Shared/FileReader.cs
> +            .ToDictionary(file => file, file => File.ReadAllText(file));
خیلی راستش مساله مهمی نیست
اوکیه

2024-07-24 07:13 UTC, rajabi-m commented on full-text-search/Phase1/Program.cs
> +    private static bool LoadFilesAndIndexThem()
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/pull/2/commits/263d25820d7481ab741bbceb2a033dc95ad00a1b) رفع شد.

2024-07-24 07:14 UTC, rajabi-m commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/pull/2/commits/263d25820d7481ab741bbceb2a033dc95ad00a1b) رفع شد.

2024-07-24 07:19 UTC, HamedSY commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
نه نه منظورم "conceptual" نبود :))
منظورم مفهومی بود؛ یعنی یه اسمی که کارکرد پروژه رو مشخص کنه، اسم shared مشخص نمی‌کنه تو پروژه چه کلاسایی هست و هر چیزی می‌تونه باشه. کلا اینجور اسما که توش هر چیزی میشه گذاشت و اصلا مشخص نمی‌کنه که محتوا چیه خیلی خوب نیستن. یکی دیگه از این اسما utility عه که خیلی توصیه نمیشه استفاده ازش

2024-07-24 07:34 UTC, rajabi-m commented on full-text-search/Shared/Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
توی [این کامیت](https://github.com/Star-Academy/Summer1403-SE-Team06/pull/2/commits/6a4bbb4b7e3f97b00e6f9f00caeafe5da70ee2ce) اسمشو گذاشتیم DomcumentManagement.

2024-07-24 07:55 UTC, merged